var json = { link_url: 'https://www.reddit.com/r/testingground4bots/comments/82zr41/test_for_stocktickerbot/',
  subreddit_id: 't5_2zqqr',
  approved_at_utc: null,
  edited: false,
  mod_reason_by: null,
  banned_by: null,
  removal_reason: null,
  link_id: 't3_82zr41',
  link_author: 'WhatEverOkFine',
  likes: null,
  replies: [],
  user_reports: [],
  saved: false,
  id: 'dve1e02',
  banned_at_utc: null,
  mod_reason_title: null,
  gilded: 0,
  archived: false,
  report_reasons: null,
  author:  { name: 'WhatEverOkFine' },
  num_comments: 1,
  can_mod_post: false,
  parent_id: 't3_82zr41',
  score: 1,
  approved_by: null,
  over_18: false,
  mod_note: null,
  collapsed: false,
  body: 'what about $AAPL or $MSFT or $GE?',
  link_title: 'test for stock-ticker-bot',
  author_flair_css_class: null,
  downs: 0,
  is_submitter: true,
  collapsed_reason: null,
  body_html: '<div class="md"><p>what about $AAPL?</p>\n</div>',
  distinguished: null,
  stickied: false,
  can_gild: true,
  subreddit:  { display_name: 'testingground4bots' },
  name: 't1_dve1e02',
  score_hidden: false,
  permalink: '/r/testingground4bots/comments/82zr41/test_for_stocktickerbot/dve1e02/',
  num_reports: null,
  link_permalink: 'https://www.reddit.com/r/testingground4bots/comments/82zr41/test_for_stocktickerbot/',
  no_follow: true,
  created: 1520564451,
  author_flair_text: null,
  quarantine: false,
  created_utc: 1520535651,
  subreddit_name_prefixed: 'r/testingground4bots',
  controversiality: 0,
  mod_reports: [],
  subreddit_type: 'public',
  ups: 1 };

module.exports = json;
